/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * consultar_clientes.java
 *
 * Created on 07/01/2004, 12:41:25
 */

package livraria;
import java.awt.*;
import java.sql.*;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.*;
/**
 *
 * @author root
 */
public class consultar_clientes extends javax.swing.JFrame {
int item=0;
 private Connection cn;
    private String CodMateria = "";
    /** Creates new form consultar_clientes */
    public consultar_clientes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnFechar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tabela1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnFechar1.setText("Fechar");
        btnFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar1ActionPerformed(evt);
            }
        });

        jButton1.setText("cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(btnFechar1)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela1.setEnabled(false);
        tabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela1clicaGrid(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabela1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabela1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String Query="select distinct(c.nome),sum(i.quantidade),sum(i.quantidade*p.preco)as total from cliente c,item_venda i,venda v";
       Query+=",produto p where i.cod_venda=v.cod_venda and v.cod_cliente=c.cod_cliente and p.cod_produto=i.cod_produto";
       Query+=" group by c.cod_cliente";
       System.out.println(Query);
       pesquisaTabela(Query);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabela1clicaGrid(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela1clicaGrid
        pegaValor();
}//GEN-LAST:event_tabela1clicaGrid

    private void btnFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar1ActionPerformed
Telas.TelaConsultaCliente.setVisible(false);
        Telas.TelaPrincipal.setVisible(true);
}//GEN-LAST:event_btnFechar1ActionPerformed
private void pesquisaTabela(String query) {
        Statement comm;
	ResultSet resultSet;
         Connection cn = conexao.getConnection();
	try {

            comm=cn.createStatement();
          //  comm = cn.createStatement();
            resultSet = comm.executeQuery(query);
            exibeDados(resultSet);
            comm.close();
        }
	catch (SQLException sqlex) {
            sqlex.printStackTrace();
	}
    }

    private void exibeDados(ResultSet rs) throws SQLException {
        // Posiciona para o primeiro registro
	boolean registros = rs.next();
	// Verifica se a tabela cont�m registros
	if (!registros) {
            JOptionPane.showMessageDialog(this, "Tabela vazia!" );
            setTitle("Sem registros para exibir" );
            return;
	}
	setTitle("Materias");
	Vector colunas = new Vector();
	Vector linhas = new Vector();

	try {
            // Monta cabe�alhos das colunas
           ResultSetMetaData rsmd = rs.getMetaData();
           for (int i = 1; i <= rsmd.getColumnCount(); ++i) {
             // colunas.addElement(trataNomeColuna(rsmd.getColumnName(i)));
              colunas.addElement(rsmd.getColumnName(i));

           }
            do {

                linhas.addElement(recuperaDados(rs, rsmd));
                System.out.println(linhas+""+colunas);
            } while (rs.next());
System.out.println(linhas+""+colunas);
            // Exibe os dados
            tabela1 = new JTable(linhas, colunas);
            JScrollPane scroller = new JScrollPane(tabela1);
           getContentPane().add(scroller, BorderLayout.CENTER);
            validate();
        }
	catch (SQLException sqlex) {
            sqlex.printStackTrace();
	}
    }

    private Vector recuperaDados(ResultSet rs, ResultSetMetaData rsmd)
        throws SQLException	{
	Vector dadosTabela = new Vector();
	for (int i = 1; i <= rsmd.getColumnCount(); ++i) {
            dadosTabela.addElement(rs.getString(i));
	}
	return dadosTabela;
    }

    private void fechaConexao() {
        try {
            cn.close();
	}
	catch (SQLException sqlex) {
            System.err.println( "N�o foi poss�vel encerrar a conex�o." );
            sqlex.printStackTrace();
	}
    }

    private void pegaValor() {
        int row=0;
	int col = 0;
        System.out.println("to no pegavalor");
	try {
            row = tabela1.getSelectedRow();
            if (row >= 0) {
                Object data = tabela1.getValueAt(row, col);
		CodMateria = data.toString();
                System.out.println(CodMateria);
            }
	}
	catch(Exception e) {
            CodMateria = "";
	}
        System.out.println("row " + CodMateria);
    }
      public String getCodMateria() {
        return CodMateria;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultar_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable tabela1;
    // End of variables declaration//GEN-END:variables

}
