/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pricipal.java
 *
 * Created on 09/12/2010, 07:38:45
 */

package livraria;

/**
 *
 * @author estagio
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Pricipal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livraria/Logomarca da Infinitive cÃ³pia.gif"))); // NOI18N

        jMenu1.setText("Cadastra");

        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamarcliente(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem7.setText("Cadastrar Editora");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamareditora(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Cadastrar Produto");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamarproduto(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Sair");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vendas e Compra");

        jMenuItem4.setText("Realizar venda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazervenda(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Realizar compra");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazercompra(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Incluir Compra");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluircompra(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultar");

        jMenuItem2.setText("Consultar Editoras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultareditoras(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Consultar clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarcliente(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chamarcliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamarcliente
      
     if(Telas.TelaCliente != null){
      Telas.TelaCliente.setVisible(true);
        }else{
          Telas.TelaCliente = new Cadastro_cliente();
          Telas.TelaCliente.setVisible(true);
         }
     Telas.TelaPrincipal.setVisible(false);
    }//GEN-LAST:event_chamarcliente

    private void chamareditora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamareditora
     //  new editora_cadastro().setVisible(true);
     if(Telas.TelaEditora != null){
      Telas.TelaEditora.setVisible(true);
        }else{
          Telas.TelaEditora = new editora_cadastro();
          Telas.TelaEditora.setVisible(true);
         }
     Telas.TelaPrincipal.setVisible(false);
    }//GEN-LAST:event_chamareditora

    private void chamarproduto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamarproduto
       // new Produto_Cadastro().setVisible(true);
     if(Telas.TelaProduto != null){
      Telas.TelaProduto.setVisible(true);
        }else{
          Telas.TelaProduto = new Produto_Cadastro();
          Telas.TelaProduto.setVisible(true);          
         }
     Telas.TelaPrincipal.setVisible(false);
    }//GEN-LAST:event_chamarproduto

    private void fazervenda(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazervenda
        //new Venda_efetuada().setVisible(true);
        if(Telas.TelaVenda != null){
            Telas.TelaVenda.setVisible(true);
        }else{
          Telas.TelaVenda = new Venda_efetuada();
          Telas.TelaVenda.setVisible(true);          
         }       
        Telas.TelaPrincipal.setVisible(false);
    }//GEN-LAST:event_fazervenda

    private void fazercompra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazercompra
        //new compra_feita().setVisible(true);
        if(Telas.TelaCompra != null){
            Telas.TelaCompra.setVisible(true);
        }else{
          Telas.TelaCompra = new compra_feita();
          Telas.TelaCompra.setVisible(true);          
         }       
        Telas.TelaPrincipal.setVisible(false);
    }//GEN-LAST:event_fazercompra

    private void incluircompra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluircompra
     //new incluir_compra().setVisible(true);
             if(Telas.TelaIncluirCompra != null){
            Telas.TelaIncluirCompra.setVisible(true);
        }else{
          Telas.TelaIncluirCompra = new incluir_compra();
          Telas.TelaIncluirCompra.setVisible(true);          
         }       
        Telas.TelaPrincipal.setVisible(false);
    }//GEN-LAST:event_incluircompra

    private void consultareditoras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultareditoras
       // new consulta_editora().setVisible(true);
             if(Telas.TelaConsultaEditora != null){
            Telas.TelaConsultaEditora.setVisible(true);
        }else{
          Telas.TelaConsultaEditora = new consulta_editora();
          Telas.TelaConsultaEditora.setVisible(true);          
         }       
        Telas.TelaPrincipal.setVisible(false);
    }//GEN-LAST:event_consultareditoras

    private void consultarcliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarcliente
       //new consultar_clientes().setVisible(true);
         if(Telas.TelaConsultaCliente != null){
            Telas.TelaConsultaCliente.setVisible(true);
        }else{
          Telas.TelaConsultaCliente = new consultar_clientes();
          Telas.TelaConsultaCliente.setVisible(true);          
         }       
        Telas.TelaPrincipal.setVisible(false);
    }//GEN-LAST:event_consultarcliente

    private void Sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair
        dispose();
    }//GEN-LAST:event_Sair

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Telas.TelaPrincipal = new Principal();
                Telas.TelaPrincipal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

}
